dev_connection:
  outputs:
    dev:
      type: bigquery
      method: oauth
      execution_project: data-geeking-gcp
      project: data-geeking-gcp
      dataset: the_look_dev
      location: US
  target: dev
prod_connection:
  outputs:
    prod:
      type: bigquery
      method: oauth
      execution_project: data-geeking-gcp
      project: data-geeking-gcp
      dataset: the_look_prod
      location: US
  target: prod
