dev_connection:
  outputs:
    dev:
      type: bigquery
      method: oauth
      execution_project: data-geeking-gcp
      project: data-geeking-gcp
      dataset: the-look-dev
      location: EU
  target: dev
prod_connection:
  outputs:
    prod:
      type: bigquery
      method: oauth
      execution_project: data-geeking-gcp
      project: data-geeking-gcp
      dataset: the-look-prod
      location: EU
  target: prod